### ISSUE TITLE
Wither ore cannot be found  solved in new update

### ISSUE THREAD

**Issue by MisterGamerDeveloper** [SmartStreamLabs/Spawn-Reborn#1]
The wither ore does not spawn. I have searched several places but I can't find anything.

**Comment by SmartStreamLabs** [comment]
Hey! [MisterGamerDeveloper](https://github.com/MisterGamerDeveloper) i have send this report to my developer team. you will get a message back soon as possible.

**Comment by SmartStreamLabs** [comment]
Hey [MisterGamerDeveloper](https://github.com/MisterGamerDeveloper)  This is indeed a mistake on our part. we will fix this as soon as possible in the next update! We are sorry.

**Comment by MisterGamerDeveloper** [comment]
ok thank you! when will the update come ?

**Comment by SmartStreamLabs** [comment]
The update come in: April ( Curseforge & Modrinth )

**Comment by MisterGamerDeveloper** [comment]
alright thanks! i will wait for the update

**Comment by SmartStreamLabs** [comment]
Your welcome! and thank you for the bug report.

**Comment by MisterGamerDeveloper** [comment]
no problem
