### ISSUE TITLE
Bugged texure

### ISSUE THREAD

**Issue by MisterGamerDeveloper** [SmartStreamLabs/Spawn-Reborn#2]
The new warm pig have a texure bug on his head 
![Schermafbeelding 2024-04-19 114015](https://github.com/ActiveReward/Spawn-Reborn/assets/167417450/7dbda1ce-8182-497a-8d17-5a3deb08f10e)

**Comment by SmartStreamLabs** [comment]
Hey [MisterGamerDeveloper](https://github.com/MisterGamerDeveloper)! Thank you for reporting this weird texure bug. i will send this bug to my developers.

**Comment by SmartStreamLabs** [comment]
[MisterGamerDeveloper](https://github.com/MisterGamerDeveloper) We will fix this bug in the new update!
