### ISSUE TITLE
texture fault

### ISSUE THREAD

**Issue by SmartLabsBuildSystemCommanderProgrammer** [SmartStreamLabs/Spawn-Reborn#4]
armored piglin texture fault on his total head

![Schermafbeelding 2024-04-19 150928](https://github.com/ActiveReward/Spawn-Reborn/assets/167438537/119ee4cf-9f49-4548-8c58-95f06c9a8069)
![Schermafbeelding 2024-04-19 150800](https://github.com/ActiveReward/Spawn-Reborn/assets/167438537/ba87dd31-909d-4797-b2b3-402167fd2a38)
![Schermafbeelding 2024-04-19 150515](https://github.com/ActiveReward/Spawn-Reborn/assets/167438537/2dce638e-84b2-4fe0-983d-5ab6407936a5)
![imageut](https://github.com/ActiveReward/Spawn-Reborn/assets/167438537/84b6808c-9d33-4417-94cd-afe41265ec3e)
![image](https://github.com/ActiveReward/Spawn-Reborn/assets/167438537/4b9fa571-3c8c-4794-8a0c-567baaeabf84)

**Comment by SmartStreamLabs** [comment]
This texture error should be addressed with more information soon.

**Comment by SmartStreamLabs** [comment]
Hey We are fixing the texture issue, thank you again for reporting! you can fix this texture by downloading the new version soon.
