### ISSUE TITLE
bug met herobrine

### ISSUE THREAD

**Issue by SmartLabsBuildSystemCommanderProgrammer** [SmartStreamLabs/Spawn-Reborn#5]
Herobrine is not attacking me even though he should

**Comment by SmartStreamLabs** [comment]
Hey [SmartStreamLabstesterCamusfade](https://github.com/SmartStreamLabstesterCamusfade), This bug have been fixed in the new bug fix update. You can download it here: [https://modrinth.com/mod/mysticrift-mobspawner-spawn-eggs/versions#all-versions](url)
